CREATE TABLE public.tb_delivery (
    date_time_delivery timestamp(6) with time zone,
    id bigint NOT NULL,
    supplier_id uuid
);


--
-- Name: tb_delivery_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_delivery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_delivery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_employee; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_employee (
    birth_date date NOT NULL,
    status smallint NOT NULL,
    cpf bigint NOT NULL,
    id bigint NOT NULL,
    phone_number bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    CONSTRAINT tb_employee_status_check CHECK (((status >= 0) AND (status <= 3)))
);


--
-- Name: tb_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_employee_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_employee_role (
    employee_id bigint NOT NULL,
    role_id bigint NOT NULL
);


--
-- Name: tb_payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_payment (
    payment_method smallint,
    payment_status smallint,
    id bigint NOT NULL,
    moment timestamp(6) with time zone,
    sale_id bigint,
    CONSTRAINT tb_payment_payment_method_check CHECK (((payment_method >= 0) AND (payment_method <= 3))),
    CONSTRAINT tb_payment_payment_status_check CHECK (((payment_status >= 0) AND (payment_status <= 2)))
);


--
-- Name: tb_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_product (
    price double precision NOT NULL,
    stock integer NOT NULL,
    bar_code bigint NOT NULL,
    id bigint NOT NULL,
    img_url text NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: tb_product_delivery; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_product_delivery (
    delivery_id bigint NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: tb_product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_role (
    id bigint NOT NULL,
    authority character varying(255)
);


--
-- Name: tb_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_sale; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_sale (
    sale_status smallint,
    employee_id bigint,
    id bigint NOT NULL,
    sale_moment timestamp(6) with time zone,
    CONSTRAINT tb_sale_sale_status_check CHECK (((sale_status >= 0) AND (sale_status <= 2)))
);


--
-- Name: tb_sale_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_sale ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_sale_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_sale_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_sale_item (
    price double precision NOT NULL,
    quantity integer NOT NULL,
    product_id bigint NOT NULL,
    sale_id bigint NOT NULL
);


--
-- Name: tb_supplier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_supplier (
    cep integer NOT NULL,
    cnpj bigint NOT NULL,
    phone_number bigint NOT NULL,
    id uuid NOT NULL,
    address character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: tb_delivery tb_delivery_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_delivery
    ADD CONSTRAINT tb_delivery_pkey PRIMARY KEY (id);


--
-- Name: tb_employee tb_employee_cpf_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_employee
    ADD CONSTRAINT tb_employee_cpf_key UNIQUE (cpf);


--
-- Name: tb_employee tb_employee_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_employee
    ADD CONSTRAINT tb_employee_email_key UNIQUE (email);


--
-- Name: tb_employee tb_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_employee
    ADD CONSTRAINT tb_employee_pkey PRIMARY KEY (id);


--
-- Name: tb_employee_role tb_employee_role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_employee_role
    ADD CONSTRAINT tb_employee_role_pkey PRIMARY KEY (employee_id, role_id);


--
-- Name: tb_payment tb_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_payment
    ADD CONSTRAINT tb_payment_pkey PRIMARY KEY (id);


--
-- Name: tb_product tb_product_bar_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_product
    ADD CONSTRAINT tb_product_bar_code_key UNIQUE (bar_code);


--
-- Name: tb_product_delivery tb_product_delivery_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_product_delivery
    ADD CONSTRAINT tb_product_delivery_pkey PRIMARY KEY (delivery_id, product_id);


--
-- Name: tb_product tb_product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_product
    ADD CONSTRAINT tb_product_pkey PRIMARY KEY (id);


--
-- Name: tb_role tb_role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_role
    ADD CONSTRAINT tb_role_pkey PRIMARY KEY (id);


--
-- Name: tb_sale_item tb_sale_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_sale_item
    ADD CONSTRAINT tb_sale_item_pkey PRIMARY KEY (product_id, sale_id);


--
-- Name: tb_sale tb_sale_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_sale
    ADD CONSTRAINT tb_sale_pkey PRIMARY KEY (id);


--
-- Name: tb_supplier tb_supplier_cnpj_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_supplier
    ADD CONSTRAINT tb_supplier_cnpj_key UNIQUE (cnpj);


--
-- Name: tb_supplier tb_supplier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_supplier
    ADD CONSTRAINT tb_supplier_pkey PRIMARY KEY (id);


--
-- Name: tb_sale fk20unxq4gx5kiemos3y4yrv285; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_sale
    ADD CONSTRAINT fk20unxq4gx5kiemos3y4yrv285 FOREIGN KEY (employee_id) REFERENCES public.tb_employee(id);


--
-- Name: tb_employee_role fk5a1thqkyfisgd225gsrauel61; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_employee_role
    ADD CONSTRAINT fk5a1thqkyfisgd225gsrauel61 FOREIGN KEY (employee_id) REFERENCES public.tb_employee(id);


--
-- Name: tb_payment fkhl0nnsn2x5cqc4avi989dfh8r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_payment
    ADD CONSTRAINT fkhl0nnsn2x5cqc4avi989dfh8r FOREIGN KEY (sale_id) REFERENCES public.tb_sale(id);


--
-- Name: tb_product_delivery fkhm7914pwx8wk680kvv328pkb2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_product_delivery
    ADD CONSTRAINT fkhm7914pwx8wk680kvv328pkb2 FOREIGN KEY (delivery_id) REFERENCES public.tb_delivery(id);


--
-- Name: tb_sale_item fkm127ckuaearcl3vyfxnb8e2i6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_sale_item
    ADD CONSTRAINT fkm127ckuaearcl3vyfxnb8e2i6 FOREIGN KEY (sale_id) REFERENCES public.tb_sale(id);


--
-- Name: tb_product_delivery fkngr6x4wwp28k0ppp8p5eoucc5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_product_delivery
    ADD CONSTRAINT fkngr6x4wwp28k0ppp8p5eoucc5 FOREIGN KEY (product_id) REFERENCES public.tb_product(id);


--
-- Name: tb_employee_role fkpivoptm0s5gsnqtel1xc5tjwg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_employee_role
    ADD CONSTRAINT fkpivoptm0s5gsnqtel1xc5tjwg FOREIGN KEY (role_id) REFERENCES public.tb_role(id);


--
-- Name: tb_delivery fkt0kndbhgytpc47lelhy2tg5yk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_delivery
    ADD CONSTRAINT fkt0kndbhgytpc47lelhy2tg5yk FOREIGN KEY (supplier_id) REFERENCES public.tb_supplier(id);


--
-- Name: tb_sale_item fkty6njf75edhxfqch4el0djkq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_sale_item
    ADD CONSTRAINT fkty6njf75edhxfqch4el0djkq FOREIGN KEY (product_id) REFERENCES public.tb_product(id);


--
-- PostgreSQL database dump complete
--

